---
project_name: beanstool

version: 2

env:
  - CGO_ENABLED=0

builds:
  - id: beanstool
    dir: .
    binary: beanstool
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - linux
      - windows
    hooks:
      pre:
        - cmd: make clean

checksum:
  name_template: checksums.txt

release:
  draft: true

announce:
  skip: true
