---
name: test
on: [push, pull_request]
jobs:
  all:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v5
    - name: Install beanstalkd
      run: sudo apt-get update && sudo apt-get install -y beanstalkd && sudo systemctl status beanstalkd
    - name: Setup go
      uses: actions/setup-go@v6
      with:
        go-version: '1.24'
    - name: Compile binaries
      run: make build
    - name: Run tests
      run: make test
    - name: Run go vet
      run: make vet
